GET http://localhost:3000/rooms/

###
GET http://localhost:3000/rooms/620d9bf4f6f6211adb2862da

###
POST http://localhost:3000/rooms
Content-Type: application/json

{
    "name": "Room 3",
    "description": "The room beside rooom 1."
}

###
DELETE http://localhost:3000/rooms/620cbd130c0b243eff3ad2b9

###
PATCH http://localhost:3000/rooms/620cbd130c0b243eff3ad2b9
Content-Type: application/json

{
    "name": "Room 2"
}

###
POST http://localhost:3000/bookings
Content-Type: application/json

{
        "roomId": "620d9bf4f6f6211adb2862da",
        "name": "Johann Smith",
        "notes": "Test Demo",
        "startDate": 1645150951827,
        "endDate": 1645153951827
}

### get booking details
GET http://localhost:3000/bookings/620d9bf4f6f6211adb2862da

### Get all bookings by room id
GET http://localhost:3000/bookings/room/620d9bf4f6f6211adb2862da